name: CI

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main

# cancel older runs for the same branch/PR when a new commit arrives
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# principle of least privilege for GITHUB_TOKEN
permissions:
  contents: read

env:
  CI: true

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.0
          run_install: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          check-latest: true # get latest patch
          # auto caching is on

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Cache ESLint results
        uses: actions/cache@v4
        with:
          path: .eslintcache
          key: eslint-${{ runner.os }}-node${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml', '.eslintrc*', 'eslint.config.*') }}
          restore-keys: |
            eslint-${{ runner.os }}-node${{ steps.setup-node.outputs.node-version }}-
            eslint-${{ runner.os }}-
            eslint-

      - name: Run ESLint
        run: |
          pnpm lint --cache --cache-location .eslintcache